<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="25.3.4" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AgentFox.Plugins\AgentFox.Plugins.csproj" />
  </ItemGroup>

</Project>
